### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by machond** [MajkiIT/polish-ads-filter#12976]
### Zrzut ekranu
![adblock](https://user-images.githubusercontent.com/44931854/56294760-e087e080-612b-11e9-930a-7e3ed5b30e48.PNG)

### Link bezpośredni
https://shinden.pl/epek/34848-shingeki-no-kyojin-2nd-season/view/158822#column-one-inner

### Co trzeba zrobić, aby pojawił się element, reklama albo błąd?
1. Wejść na stronę i wcisnąć oglądanie na playerze
2. Wywali komunikat" Och... Przeglądarka zrobłia blokowanie treści (prywatność). Albo któryś dodatewk. Albo antywirus. Albo zmiany w /etc/hosts."

### Moja konfiguracja
**Przeglądarka internetowa:** Chrome

**Rozszerzenia i skrypty:** nano + defender

**Listy filtrów:**
1. EasyList
2. Oficjalne Polskie Filtry do Adblocka, uBlocka Origin i AdGuarda
3. Oficjalne polskie filtry przeciwko alertom o Adblocku

**Inne ważne informacje mogące mieć znaczenie (opcjonalne):**
Było to już i znowu naprawili.

**Comment by krystian3w** [comment]
Shinded.pl może do KAD by ktoś nie podchwycił pomysłu i zrobił "pishing".

**Comment by machond** [comment]
To gierka słowna od shinden dead ;P

P.s. 
A tak poważnie, to już poprawiam.

**Comment by MajkiIT** [comment]
@krystian3w masz to ?

**Comment by krystian3w** [comment]
Tak, trzeba założyć konto i nie chce wskoczyć odtwarzacz...

Niestety nie jestem ustalić co wykrywają jakby znowu bug, że czegoś nie widać w loggerze.

**Comment by machond** [comment]
Jakieś postępy w tej kwestii? ; )

**Comment by krystian3w** [comment]
Hmm... AdGuard pod shinden w trybie blokowania tylko na określonych domenach (odwrócona biała lista). 

Pewnie wymóg posiadania konta utrudnia analizę.

**Comment by DiabloPiotr** [comment]
https://shinden.pl/episode/10831-steins-gate/view/87288#column-one-inner
Spróbujcie na tym linku. Ten sam problem a nie wymaga konta. Założenie fake konta to chwila i zapamiętanie danych w chrome więc to łatwo da się obejść. Blocker to inna sprawa.

**Comment by krystian3w** [comment]
Problem że w AdGuard to ogrania ktoś kto umie w JavaScript, a my się bawimy w 20 dopuszczeń i 10 nowych metod zablokowania i to na poziomie filtrów ABP.

**Comment by DeEpicOfGames** [comment]
Nie znam się na robieniu filtrów do adblocka, ale poświęciłem wczorajszy wieczór na naukę javascriptu i na zrobiłem wtyczkę która rozwiązuję problem z blokadą odtwarzaczy przez shindena, daje link do [repo](https://github.com/DeEpicOfGames/Shinden-unlocker-anti-adblock-bypass).

**Comment by krystian3w** [comment]
Dobre https://www.youtube.com/watch?v=C8syChSo-DY&t=4s

**Comment by DiabloPiotr** [comment]
@DeEpicOfGames Rozważ dodanie opcji zmiany odtwarzacza (nie jest to możliwe bez ponownego załadowania strony), oraz przycisk umożliwiający stałe wyłączenie powiadomień.

**Comment by DeEpicOfGames** [comment]
@DiabloPiotr u mnie działa zmiana odcinka bez odświeżania strony, tylko trzeba odczekać te 5 sekund po zamknięciu box'a bo blokuje on kod, co do powiadomień to albo  je usunę albo zastąpię je odliczaniem gdzieś na stronie

**Comment by DiabloPiotr** [comment]
@DeEpicOfGames Rozszerzenie automatycznie się usuwa. Tylko u mnie występuje taki problem?

**Comment by krystian3w** [comment]
Może łamie nowe coś, niby mi jakiś taki głupi mail przysłali:


> Hello,
> 
> You are receiving this email because you are registered as the developer of an extension for Firefox.
> 
> We will be updating our add-on policy and clarifying our blocking process as part of our work to [make add-ons safer for Firefox users](). This is a summary of the changes that will go into effect on June 10, 2019.
> 
> * We will no longer accept extensions that contain obfuscated code. We will continue to allow minified, concatenated, or otherwise machine-generated code as long as the source code is included. Please see our updated source code submission page for more details.
> * Continued use of obfuscated code may result in your add-on being blocked.
> 
> We will also be clarifying our blocking process. Add-on or extension blocking (sometimes referred to as “blocklisting”), is a method for disabling extensions or other third-party software that has already been installed by Firefox users.
> 
> * We will be blocking extensions more proactively if add-ons are found to be in violation of our policies. We will be casting a wider net, and will err on the side of user security when determining whether or not to block.
> * We will continue to block extensions for intentionally violating our policies, critical security vulnerabilities, and will also act on extensions compromising user privacy or circumventing user consent or control.
> 
> You can preview [the policy]() documents and ensure your extensions abide by them to avoid any disruption.
> 
> Thank you for your help in keeping the add-ons ecosystem safe. If you have questions about these updated policies or would like to provide feedback, please post to this [forum thread]().
> 
> Regards,
> 
> The Add-ons Team
> 

A tak to najlepiej sprawdzić czy twój twardziej / półprzewodnik może nie przechodzi na emeryturę.

**Comment by DiabloPiotr** [comment]
Hmmmm. Po wrzuceniu do folderu z pozostałymi rozszerzeniami, cały folder został usunięty (to samo stało się u znajomego), jednak po zmianie nazwy na podobną do pozostałych rozszerzeń i dodaniu ponownie wszystko pozostaje na miejscu.

**Comment by garggul** [comment]
> DiabloPiotr :  https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489275784 + https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489288778


Jak widać nie tylko u ciebie tak jest, bo u mnie też, w Mozilli mają jakąś awarię z certyfikatami i dodatki się wyłączają i nie działają.

U mnie taki zonk, że przed chwilą nagle w Firefox wyłączyło wszystkie dodatki, a jeszcze kilka minut temu działały:

<details not-open>
<summary>zrzut ekranu 1</summary>

![ss_002](https://user-images.githubusercontent.com/50133507/57175654-c1d55980-6e4e-11e9-802e-d79db3a9fd35.png)

</details>

Z kolei po kliknięciu w link [Więcej informacji o zmianach w dodatkach](https://support.mozilla.org/pl/kb/modernizacja-technologii-dodatkow-dla-firefoksa?as=u&utm_source=inproduct) jest komunikat o awarii:

<details not-open>
<summary>zrzut ekranu 2</summary>

Due to a certificate issue, add-ons are not working and will fail to install. We are currently working on this issue and you can track updates at https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/ 

Ze względu na problem z certyfikatem dodatki nie działają i instalacja nie powiedzie się. Obecnie pracujemy nad tym problemem i możesz śledzić aktualizacje na stronie

![ss_003](https://user-images.githubusercontent.com/50133507/57175755-b0d91800-6e4f-11e9-9654-086e2ec97f38.png)

</details>

Z kolei po kliknięciu w link: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/ kolejny komunikat o awarii z opisem awarii:

<details not-open>
<summary>zrzut ekranu 3</summary>

At about 6:10 PST we received a report that a certificate issue for Firefox is causing add-ons to stop working and add-on installs to fail.

Około 6:10 PST otrzymaliśmy raport, że problem z certyfikatem dla Firefoksa powoduje, że dodatki przestają działać, a instalacje dodatkowe nie działają.

Our team is actively working on a fix. We will update as soon as we have more information.

![ss_004](https://user-images.githubusercontent.com/50133507/57175790-38bf2200-6e50-11e9-93c2-9839f7e056c5.png)

</details>

**Comment by krystian3w** [comment]
Dysk też bym sprawdził, dodatek to jeden plik w profilu, więc łatwo by go szlag trafił i znikał.

**Comment by krystian3w** [comment]
Dodatkowo nie bawcie się w ustawianie daty na klika miesiecy do tyłu lub do przodu, bo też wam "padnie" certyfikat - np. miałem tak z Nano Adblockerem i Nano Defenderem i potem batalia by z profilu wyciągnąć plik XPI tych dodatków by je aktywować bez straty "ustawień".

**Comment by garggul** [comment]
Co do anty-adblocka to:
```
@@||static.criteo.net/js/ld/publishertag.js$script,third-party,domain=shinden.pl
@@||www.rfmbvlaphdud.com/nn.js$script,third-party,domain=shinden.pl
@@||www.ffpnlrnmfyeqx.com/awj.js$script,third-party,domain=shinden.pl
@@||www.lpbyadpvf.com/up.js$script,third-party,domain=shinden.pl
```

Generalnie to wystarczą 2: ma być ten pierwszy + jeden z losowych, ale że losowe się co jakiś czas zmieniają to dałem wszystkie losowe jakie wyłapałem, aktualnie 3, ale może być ich więcej.

**Comment by krystian3w** [comment]
To może lepiej bez domen, i tak pewnie wykorzystają jakiś inny plik do reklam kiedyś?

```
@@/nn.js$script,third-party,domain=shinden.pl
@@/awj.js$script,third-party,domain=shinden.pl
@@/up.js$script,third-party,domain=shinden.pl
```

**Comment by krystian3w** [comment]
@garggul a coś na `https://flashdeals.aliexpress.com/en.htm?aff_platform=promotion`?

**Comment by krystian3w** [comment]
Niby na aliexpress pomoże też:

```
shinden.pl##body > div[style^="position: fixed; display: block; width: 100%; height: 100%;"]:last-of-type
```

**Comment by garggul** [comment]
Nie mam tego aliexpress, jak je zreprodukować.

**Comment by krystian3w** [comment]
np. klikając w przycisk play odtwarzania ja niby pod coś mam podpięty jednorazowy "Event listener".

Nawet kontenery Firefox pozwalają mi to reprodukować w kółko:  https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers

**Comment by garggul** [comment]
- po pierwsze najpierw uaktualniłem mój wcześniejszy komentarz https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489316822 o 2 kolejne losowe domeny, więc trzeba ukaktualnić też ten https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489317031
- na Operze tego nie mam...
- na Firefox nie miałem jak sprawdzić przez tę awarię bo wywaliło wszystkie dodatki
- ale już naprawili awarię, więc sprawdziłem teraz i faktycznie wyskakuje popup
- tyle, że u mnie jest pusty "about:blank", ale to raczej kwestia drugorzędna
- nie trzeba klikać w "krystian3w: przycisk play odtwarzania", żeby wywołać popupa, wystarczy kliknąć gdziekolwiek na stronie...
- popup jest wywoływany przez zwykły statycznie osadzony skrypt PopAds, który po prostu siedzi sobie w kodzie strony oczywiście zaciemniony, jak cały anty-adblock 
- antidotum inne niż podane w https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489317221 i w https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489317622 to będzie jedno z tych do wyboru:

1 `shinden.pl##^script:has-text(PopAds%20CGAPIL%20A)` (jeśli u innych też nie pojawia się popup na Chromowatych)
2 `shinden.pl##+js(popads-dummy.js)`
3 `shinden.pl##+js(addEventListener-defuser.js, click)` jeszcze nie rozgryzłem drugiego parametru do przekazania, bo nie miałem czasu, więc w tej chwili nie nadaje się bo oprócz popupa, nie będzie działało cokolwiek na co klikniemy, ale podaję może zanim ja się tym zajmę, to komuś będzie chciało się pobawić)
4 combo:
-`shinden.pl##+js(window.open-defuser.js, 0, /[a-zA-Z0-9-]/)` (na pusty popup - przypadek u mnie)
-`shinden.pl##+js(window.open-defuser.js, , flashdeals.aliexpress.com/en.htm?aff_platform=promotion`) na niepusty czyli zawierający jakiś link - przypadek u krystian3w)

**Comment by krystian3w** [comment]
To jak wyłapiesz z 10 nowych to licz ile ma znaków nazwa domeny i plik, może regex nie przepuści za dużo plików co mają nazwę z 2-4 znaków.

**Comment by krystian3w** [comment]
`|^htt(p|s)` to chyba jest złe...:

`http://`
`htts://`

albo znowu nie umiem w regex.

**Comment by garggul** [comment]
Dziwne, bo co tam niby może być źle, zawsze robiłem filtry z krótszym `^htt(p|s)` zamiast długiego `^(http|https)` i działało, jeśli nie działa to spróbuj dłuższą wersję.

**Comment by krystian3w** [comment]
```
https://www.oezgivtasc.com/zrx.js
```

**Comment by garggul** [comment]
<details not-open>
<summary>Czasem przy pierwszym wejściu (wyczyszczone ciasteczka & kecz), strona się nie ładuje, jest biała & pusta i sypie błędem "403 Forbidden (467)", czy ktoś też tak ma:</summary>

![SS_011](https://user-images.githubusercontent.com/50133507/57295311-7e871f00-70ca-11e9-9e36-e6f9b99d03d4.png)

</details>

**Comment by krystian3w** [comment]
Też mam - olej to wina atrybutu w url i walidacji sesji.

**Comment by krystian3w** [comment]
Pingwin mówił, że serwer sprawdza te 5 sekund i on nie przeskoczy, jak dodatek też musi czekać 5 sekund oszukując API to raczej lipa.

5 sekund to mało, gorsze są te 30 s, 1 min. czy dłuższe.

**Comment by garggul** [comment]
Fakt, przed założeniem zgłoszenia na uassets, szukałem zgłoszeń o tym timerze na polskim repo i repo uassets, ale całkowicie zapomniałem, żeby przeszukać repo reeka czy pingwina, po prostu wyleciały z głowy te repa, a okazało się, że u reeka były 2 zgłoszenia z tym timerem (czerwiec 20017), a potem u pingwina jedno (maj 2018), i rzeczywiście w obydwu pingwin odpisywał, że to po stronie serwera, chociaż z drugiej strony minął już rok i mamy Maj 2019, więc coś mogło się zmienić, ale jak widać chyba nic się nie zmieniło i 5 sekundowy timer dalej jest po stronie serwera, więc zostanie z nami, widocznie zakochał się w nas.

**Comment by krystian3w** [comment]
Jak coś uprościłem regex, plik po http się nie wgra np. w większości przeglądarek z domyślną konfiguracją - strzał w kolano jak ktoś porzuci blokowanie reklam...

I na razie nie kombinują np. z wielkością liter.

**Comment by lain566** [comment]
Specific filters for uBO, adding those filters I no longer receive any anti-adblock message, 
no exception filters are necessary https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489317031
I was going to publish these filters in uAssets, but they closed the @kulfoon's issue
Can someone test it?
```
shinden.pl##+js(abort-on-property-write.js, _pop)
shinden.pl##+js(noeval-if.js, Criteo)
```

**Comment by kacperszo** [comment]
> Specific filters for uBO, adding those filters I no longer receive any anti-adblock message,
> no exception filters are necessary [#12976 (comment)](https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489317031)
> I was going to publish these filters in uAssets, but they closed the @kulfoon's issue
> Can someone test it?
> 
> ```
> shinden.pl##+js(abort-on-property-write.js, _pop)
> shinden.pl##+js(noeval-if.js, Criteo)
> ```

works for me

**Comment by krystian3w** [comment]
On mobile too!

**Comment by garggul** [comment]
> lain566 : https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491094068 : I was going to publish these filters in uAssets, but they closed the @kulfoon's issue

Hey me = kulfoon, my issue https://github.com/uBlockOrigin/uAssets/issues/5551 wasn't about the main anti-adblock issue, it was about the timer-anti-adblock issue, I clearly marked it in the spoiler in my first comment: https://github.com/uBlockOrigin/uAssets/issues/5551#issue-441272289, also after penguin missed the spoiler https://github.com/uBlockOrigin/uAssets/issues/5551#issuecomment-490304232 I clearly marked it again in my reply to him: https://github.com/uBlockOrigin/uAssets/issues/5551#issuecomment-490392512, seems you too missed the spoiler and the reply. And the issue was closed because the timer is most probably unfixable as validated on a server-side which was mentioned here https://github.com/uBlockOrigin/uAssets/issues/5551#issuecomment-490218932, here https://github.com/uBlockOrigin/uAssets/issues/5551#issuecomment-490239585 and here https://github.com/uBlockOrigin/uAssets/issues/5551#issuecomment-490778018, but feel free to try to fix it if you can.

====================================================================

As for the main anti-adblock issue you talking about, this thread is a proper place to post your solution, as this is an original polish thread, however there is also another parralel thread here: https://github.com/NanoMeow/QuickReports/issues/415 where you can post it too.

As for your solution - it's working, on both Opera & Firefox, you're like this guy https://github.com/mun3 if you decided to spent time, enter The Matrix and managed to deobfuscate this Matrix thing: https://github.com/NanoMeow/QuickReports/issues/415#issuecomment-490393798 + https://github.com/NanoMeow/QuickReports/issues/415#issuecomment-490705744, perhaps you both know Neo, Trinity and Morpheus. We hope that your solution won't break the website's functionality (we'll see and make sure as the time will pass).

> lain566 : https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491094068 : no exception filters are necessary

As seen: 
> ghajini : https://github.com/MajkiIT/polish-ads-filter/issues/8544#issuecomment-411511204 
> admin : https://github.com/MajkiIT/polish-ads-filter/issues/8544#issuecomment-411540732

polish filters prefer whitelisting solutions to keep compatibility with ABP, however sometimes scriplets solutions are chosen, I don't know which solution will be added to polish lists in case of SHINDEN, perhaps the both.

**Comment by krystian3w** [comment]
Ja bym dodał może na razie oba i dopuszczenia zabezpieczył if-em by ich nie widział uBlock Origin.

**Comment by garggul** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491319674 : ale wtedy nie wiedziałem, że trzeba by jeszcze coś na `Criteo`.

Pierwszy filtr z rozwiązania opartego na whitelistingu jest właśnie na Criteo: https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489316822 + https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-489317031, więc można było domyśleć się, że w rozwiązaniu opartym o skrypty też będzie trzeba uwalić coś z Criteo.

**Comment by krystian3w** [comment]
Mi chodzi o czas do 16 kwietnia 2019 😎.

**Comment by lain566** [comment]
> polish filters prefer whitelisting solutions to keep compatibility with ABP, however sometimes scriplets solutions are chosen, or both, I don't know which solution will be added to polish lists in case of SHINDEN.

@garggul I suggested those filters because the filter lists in this repository appear by default in uBO for Polish users, however, it does not appear by default in ABP, by default Easylist Polish appears.
`https://github.com/easylistpolish/easylistpolish`

This filter list makes use of the extended syntax for uBO
`https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt`


---

> And the issue was closed because the timer is most probably unfixable as validated on a server-side which was mentioned here uBlockOrigin/uAssets#5551 (comment), here uBlockOrigin/uAssets#5551 (comment) and here uBlockOrigin/uAssets#5551 (comment), but feel free to try to fix it if you can.

If I try to skip the countdown, I get this error
<details><summary>Screenshot</summary>

![Anotación 2019-05-10 201549](https://user-images.githubusercontent.com/27441315/57551235-d6db4c80-7368-11e9-9e4b-04cc099253a1.png)
</details>

**Comment by krystian3w** [comment]
> This filter list makes use of the extended syntax for uBO
> `https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_ublock.txt`

https://github.com/olegwukr/polish-privacy-filters/blob/master/anti-adblock-suplement.txt - should pasted here. `adblock_ublock.txt` now is for only ads and any problematic ads on site with anti-adblock we cut in `anti-adblock-suplement.txt`.

**Comment by lain566** [comment]
@krystian3w ABP is adding uBO scriptlets  to its extension, it still needs to add all.

For example, this is a specific filter for Adblock/Adblock Plus
`shinden.pl#$#abort-on-property-write _pop`

**Comment by krystian3w** [comment]
@lain566 I know but https://github.com/abp-filters/abp-filters-anti-cv reject this tikcet with anti-adblock.

**Comment by lain566** [comment]
Oh, I did not know it

**Comment by krystian3w** [comment]
https://github.com/abp-filters/abp-filters-anti-cv/issues/18#issuecomment-441550361

**Comment by lain566** [comment]
@krystian3w Thanks for the info

**Comment by krystian3w** [comment]
No problem.

**Comment by garggul** [comment]
> lain566 : https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491433350 : This filter list makes use of the extended syntax for uBO

I'm not sure whether it always makes use (even if already a whitelisting ABP compatible solution has been found) so it tries to keep both uBO and ABP comatibility at the same time, 

or only if a whitelisting ABP solution hasn't been found.

**Comment by lain566** [comment]
@garggul Yes, I know, krystian3w explained it to me, I didn't know there was another Polish filter list repository.

And going back to the other topic, you can try it yourself, if you add this filter, the countdown will start from 1, you can change the value to 0
`shinden.pl##+js(set-constant.js, value_count, 1)`

**Comment by garggul** [comment]
`shinden.pl##+js(set-constant.js, value_count, 1)`

I found myself this filter before creating this issue: https://github.com/uBlockOrigin/uAssets/issues/5551 but since the rule didn't work (an error appears), I didn't mention about it, as not worth to.

**Comment by lain566** [comment]
If you go to this link and wait 5 seconds
`https://api4.shinden.pl/xhr/581095/player_load?auth=X2d1ZXN0XzowLDUsMjEwMDAwMDAsMjU1LDQxNzQyOTM2NDQ`

you will see the player of this link, if you do it before 5 seconds, you can not see the player.
`https://api4.shinden.pl/xhr/581095/player_show?auth=X2d1ZXN0XzowLDUsMjEwMDAwMDAsMjU1LDQxNzQyOTM2NDQ`

uBO can not do anything against this (the countdown in server side)


------

> BTW Not sure what are your notifications settings for particular repositories, but in case you don't recieve ones from https://github.com/olegwukr/polish-privacy-filters/issues, seba2282 needs help with this one : olegwukr/polish-privacy-filters#67 (comment), maybe it will be a fun & challenge for you to try to bypass it.

Yes, I got the notification, I know that problem, but Nano Defender's solution does not work for uBO, because `xhr` `redirect` does not work on `player.pl`

**Comment by garggul** [comment]
Ok, so in conclusion: we got pure adblocker solutions for the Main Anti-Adblock  / Click-Popup of SHINDEN, and the Timer-Anti-Adblock of SHINDEN is unfixable in pure adblocker, because is server-side, so I consider this thread as solved as for now and we can move  (of course anybody can still comment here and continue SHINDEN related discussion if wish) to player.pl's thread, wherein I've just replied to you https://github.com/olegwukr/polish-privacy-filters/issues/67#issuecomment-491497323.

**Comment by krystian3w** [comment]
Ale po co inne rozwiązanie, osoby bez adblocka mają też to czekanie na player?

**Comment by garggul** [comment]
> krystian3w : https://github.com/MajkiIT/polish-ads-filter/issues/12976#issuecomment-491501192 :

> Ale po co inne rozwiązanie

Jakie inne?

> osoby bez adblocka mają też to czekanie na player?

No bez adblockera też jest timer.

**Comment by krystian3w** [comment]
Jeszcze możecie sprawdzić czy replace z AdGuard pomaga, niby dobre na SSAI.

https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#replace-modifier

**Comment by machond** [comment]
Problem wrócił, shinded vX ;_
![shinded2](https://user-images.githubusercontent.com/44931854/81512422-c580a380-9320-11ea-9309-7f64a3037879.PNG)
