### ISSUE TITLE
pclab.pl

### ISSUE THREAD

**Issue by F4z** [MajkiIT/polish-ads-filter#1517]
Reklama, jak kliknie się gdzieś na tym zaznaczonym miejscu, to w nowej karcie otwiera się reklama.
Strona -`http://pclab.pl/`
![image](https://cloud.githubusercontent.com/assets/11742596/20607481/11e2c316-b279-11e6-9fc0-0ec2132c33b3.png)

Na przykład:
`pclab.pl##[href^="http://csr.onet.pl/eclk/clk"]`

Swoją drogą, ta reguła już była kiedyś dodana, ale została usunięta - https://github.com/MajkiIT/polish-ads-filter/commit/7d29647346c651fa0086337ee789b870cfe0db1f#diff-711027ed0794992ae3b8710d874f3df7L577
Coś psuła?

**Comment by xxcriticxx** [comment]
umnie strona jest czarnym tlem 

filter nie pozwala nacisnac na reklama ale puste miesce zostaje

**Comment by F4z** [comment]
Tych pustych miejsc trudno się pozbyć. Kiedyś próbowałem i jeden z elementów na stronie nieprawidłowo działał, potem może jeszcze raz spróbuję.

Odnośnie tła, u mnie też jest czarne, ale dodałem sobie do Adguarda odpowiednie reguły, żeby było takie jakie jest zazwyczaj.
`pclab.pl#$#body #contenttabwrapper { background: #FFF url("http://pclab.pl/img/skin/0/top_2.png") repeat-x!important; }`
`pclab.pl#$#body #container { background: #FFF url("http://pclab.pl/img/skin/0/top_2.png") repeat-x!important; }`
`pclab.pl#$#body #footercontainer { background: url("http://pclab.pl/img/skin/0/bottom.png") 0px bottom repeat-x!important; }`

Z tego co wiem, to uBlock celowo nie obsługuje reguł, w których zmienia się styl elementu i dodaje się `url("coś")`, więc w uBlocku to nie będzie działać. No chyba, że się mylę.

**Comment by xxcriticxx** [comment]
nope nie dziala

**Comment by F4z** [comment]
Odnośnie tych pustych miejsc.
Po dodaniu tych reguł (nie działają w Adblocku) nie powinno już ich być, ale jeden z elementów nie działa prawidłowo.
`pclab.pl###header .left .sponT:style(height: 100px !important;)`
`pclab.pl###header .right .sponT:style(height: 75px !important;)`
`pclab.pl###headerwrapper:style(height: 140px !important;)`
`pclab.pl###categories:style(top: 33px !important;)`
`pclab.pl###header:style(z-index: 0 !important;)`
`pclab.pl###tabwrapper #tab:style(margin-top: 90px !important;)`

Jak kliknie się na przycisk "Rozwiń",
![image](https://cloud.githubusercontent.com/assets/11742596/20610404/6ce86e26-b299-11e6-8ff7-8252a561152c.png)

to menu rozwija się do góry. Niestety nie potrafię tego naprawić.
![image](https://cloud.githubusercontent.com/assets/11742596/20610412/9491be78-b299-11e6-94f8-6e776a2ecc20.png)

**Comment by xxcriticxx** [comment]
dokladnie tak jak @F4z napisal ale mysle ze da sie z tym zyc

**Comment by MajkiIT** [comment]
@F4z Dziękuję

a reguła została usunięta, bo dodałem regułę ##[href^="http://csr.onet.pl/eclk/clk"]

**Comment by F4z** [comment]
@MajkiIT oki doki, dzięki za odpowiedź, ale ze względu na tę regułę `@@||pclab.pl^$generichide` ogólne kosmetyczne reguły nie działają, więc trzeba było ją dodać.

Te reguły, które podałem to takie eksperymentalne, nie wiem czy czegoś nie psują.
Sprawdzałeś może jak się zachowuje Adblock Plus z tymi regułami?
U mnie przez te reguły w Adblocku w ogóle nie działają reguły kosmetyczne.
Może lepiej byłoby je dodać do listy `polskie filtry do uBlocka uzupelnienie`?

Swoją drogą, jedna z reguł blokuje logo i jakiś inny element, który nie jest reklamą.

![image](https://cloud.githubusercontent.com/assets/11742596/20623087/4aa4cfa4-b306-11e6-9cad-0c6183892291.png)

Można dodać te dwa wyjątki i powinno to wyglądać lepiej:
`@@||pclab.pl/img/extra/*_logo.$image,domain=pclab.pl`
`@@||pclab.pl/img/extra/*_header.$image,domain=pclab.pl`

![image](https://cloud.githubusercontent.com/assets/11742596/20623125/70668d9a-b306-11e6-9042-73fd95f3fad0.png)

**Comment by MajkiIT** [comment]
Ok poprawię

**Comment by xxcriticxx** [comment]
@F4z info z `https://github.com/gorhill/uBlock/wiki/Static-filter-syntax` o ile dobrze rozumiem Adguard filtry powinny dzialac

By default, the implicit purpose of cosmetic filters is to hide unwanted DOM elements. However sometimes it may be useful to re-style a specific DOM element on a page rather than hide it. Here is an recent example of such cases. This is the purpose of the new :style-based selector. The syntax is as follow:

example.com##h1:style(background-color: blue !important)

So mainly it's exactly the same syntax of plain cosmetic filters, except that the :style(...) suffix is appended at the end. The content in the parentheses must be one or more CSS property declarations (separated by the standard ;). It is not allowed to use property values with url(...), such style:-based cosmetic filters will be discarded.

As with the other new cosmetic filtering selectors, the :style can be used only for specific cosmetic filters, i.e. there must be a hostname of entity specified for the filter.

Adguard already support such feature, although using a different syntax. However uBO is able to transparently convert and make use of the Adguard's "CSS injection rules" if ever you use an Adguard filter list in uBO (well, this essentially means you can use Adguard's syntax in uBO if you prefer).

For example, Adguard English filter contains ~50 styling filters, Adguard Russian filter list contains ~250 styling filters, etc. Note that often styling filters are used to foil anti-blocker mechanism on web pages. Given this, you may want to benefit from Adguard's filter lists:

**Comment by F4z** [comment]
Tak, powinny, ale reguły z `url(...)` nie.

> It is not allowed to use property values with url(...), such style:-based cosmetic filters will be discarded.

Chyba, że coś źle rozumiem.

**Comment by xxcriticxx** [comment]
hyba dobrze rozumiesz

**Comment by Isamaul** [comment]
Hej.
Dzisiaj wpadłem na pclab - i brakło mi logo :)

`@@pclab.pl/img/extra/115_logo.png
@@pclab.pl/img/extra/115_header.png`

Przywróci się w ten sposób logo i będzie można nawigować po serwisie

**Comment by F4z** [comment]
No tak, też o tym pisałem - https://github.com/MajkiIT/polish-ads-filter/issues/1517#issuecomment-262933343
@MajkiIT widocznie zapomniał tego dodać 😛

**Comment by MajkiIT** [comment]
@F4z masz rację uleciało mi 
@@||pclab.pl/img/extra/*_logo.$image,domain=pclab.pl
@@||pclab.pl/img/extra/*_header.$image,domain=pclab.pl
