### ISSUE TITLE
panasonic-batteries.com/pl

### ISSUE THREAD

**Issue by blocker999** [MajkiIT/polish-ads-filter#21486]
( po prawo ) : https://www.panasonic-batteries.com/pl/akumulatory/akumulator-ready-use/rechargeable-ready-use-1900mah-aa

**Comment by krystian3w** [comment]
@KIBOKE locked scroll for One Trust

**Comment by kiboke** [comment]
@krystian3w I don't see a problem with this website at all, scrolling work fine on my side.

**Comment by krystian3w** [comment]
For my first visit have locked scroll:

![image](https://user-images.githubusercontent.com/35370833/224660356-6eb2b328-2c74-4076-af0b-b5f3f693139c.png)


IMO few people close page instead refresh if rest of visits will be have unlocked scroll.

**Comment by kiboke** [comment]
On my side, overflow is set to hidden if I whitelist it, but it works just fine if the pop-up is blocked. Can you check that, please?

**Comment by krystian3w** [comment]
With IDCAC only:

![image](https://user-images.githubusercontent.com/35370833/224665438-50007a43-d3c7-41f1-aa39-8be5fa564551.png)

On second visit  scrolling back, but uBo and ABP don't have option to refresh page by e.g. scriptlet so rule is really bad for ABP and AdBlock if we can't block asap some OneTrust resource/request to unlock scrolling on first visit (in uBO may works `##body,html:style(overflow: auto !important;)` to first broken e.g. video player - then needed checking to unlock load video by scriptlets).

**Comment by kiboke** [comment]
The overflow may be set to hidden by other scripts so your proposal is not good enough. I will remove the general `#onetrust-consent-sdk` filter since too many exceptions are required.

**Comment by krystian3w** [comment]
This is supposedly how the oneTrust plugin does it (so rather all others are a variation of the webmaster or OneTrust mixes something up and moves it from the style attribute to classes or shortens the length of the "root" element in the body), so this could cover the flagship scroll lock feature.

As you can, secure an exception list as if suddenly people start requiring pop-up blocking in ABP/uBO instead of accepting generically in a dedicated add-on.
