### ISSUE TITLE
dead page ok to remove 

### ISSUE THREAD

**Issue by xxcriticxx** [MajkiIT/polish-ads-filter#2401]
` seansik.nl###over-player`
 ` seb-tv.pl##center`

**Comment by xxcriticxx** [comment]
@MajkiIT jakis script by sie przydal zeby podac liste niech wyciagnie dns. jak wyciagnie dns to strona jest dobra jak nie to dead cos takiego prostego

**Comment by MajkiIT** [comment]
@xxcriticxx ok coś pomyślę jak to zrobić. Najprościej będzie wrzucić parsowanie pod względem domen, wyciągnięcie unikalnych i sprawdzenie dnsem. To co będzie brak rozwiązania dopisze do pliku.

**Comment by xxcriticxx** [comment]
zagadam z @X01X012013

**Comment by xxcriticxx** [comment]
@MajkiIT nie ktore strony dzialaj na samym ip numerze

**Comment by X01X012013** [comment]
Eh... what's going on here?

**Comment by xxcriticxx** [comment]
@X01X012013 can you make script that will check polish list for any dead domains?

**Comment by X01X012013** [comment]
Yes, I have plan on making such automation software, however, I wouldn't be hosting the software for polish list since I need to scan AdBlock Protector List and I don't have a fast Internet. It will be open source and written either in PhantomJS, Electron, or .NET.

**Comment by xxcriticxx** [comment]
whats the eta on such software?

**Comment by X01X012013** [comment]
I expect to finish making it in early May.

**Comment by MajkiIT** [comment]
@X01X012013 If you want I can add you account on my VPS. I have Ubuntu 16.04.

**Comment by X01X012013** [comment]
A fast server would definitely help, I'll see how the development goes first, I'm still working on the initial blueprint and design, I want to watch more than just if a domain still works. And I'm not sure how much resource the software will consume, if it starts to consume too much resources, I will definitely ask you for help. Thanks for the offer 😄

**Comment by xxcriticxx** [comment]
user script would do this?

**Comment by MajkiIT** [comment]
@X01X012013 Ok. If you need access to the server then write to me and I will add you an account.

**Comment by X01X012013** [comment]
@xxcriticxx 
Userscript would be fine for checking if a website is on-line, but I want to make a software that reads a filter list and extract domains that needs to be checked. I also want to watch EasyList for suspicious white-listing, and a few websites for mutations. Also I want to make the output be a file, so I can run it on a headless Linux device. 
Since scanning filter lists would be a routine thing, it would be better to properly make the automation for the long run instead of hack together a script just for now. And in the case of `seansik.nl`, it's currently down, but what if it's up in a few days? I want to build all these checks into a solid automation framework.

**Comment by xxcriticxx** [comment]
its down for about 6 months already i dont think it will come up again

**Comment by X01X012013** [comment]
I mean, the number of days a website is down should be counted by the automation system (and remove the filter entry after maybe 60 days), which isn't easy to do with Userscript.

**Comment by xxcriticxx** [comment]
no problem when you make something let us please get access
